version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: server/Dockerfile
    depends_on:
      - postgres
    networks:
      - mynetwork
    ports:
      - 8000:8000

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5400
    ports:
      - 5400:5400
    networks:
      - mynetwork
    command: -p 5400

  nginx:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
    driver: bridge
