"""empty message

Revision ID: 70657ab5f4be
Revises: 2bd09e19378a
Create Date: 2024-11-14 15:47:56.120945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70657ab5f4be'
down_revision: Union[str, None] = '2bd09e19378a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist_items', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'playlist_items', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'playlist_items', type_='unique')
    op.drop_column('playlist_items', 'name')
    # ### end Alembic commands ###
