"""empty message

Revision ID: 3015df0dfbc4
Revises: 0f8f6dea4053
Create Date: 2024-11-13 13:59:00.688442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3015df0dfbc4'
down_revision: Union[str, None] = '0f8f6dea4053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_directories_dir_name', table_name='directories')
    op.drop_index('ix_directories_dir_path', table_name='directories')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_directories_dir_path', 'directories', ['dir_path'], unique=True)
    op.create_index('ix_directories_dir_name', 'directories', ['dir_name'], unique=True)
    # ### end Alembic commands ###
